### PR TITLE
Added bi directional communication between processes

### PR DESCRIPTION
**Pull request by eternalfrustation**
This is adds support for bidirectional communication between processes

### CODE REVIEW

**Review by Tanishq-Banyal — CHANGES_REQUESTED** [review]
Your Formatting is Unacceptable

1. Use 
```
int func()
{

}
```
instead of
```
int func() {

}
```

2. And use `Tabs` not spaces (1 tab = 4
space)

3. Don't touch other codebase unnecessarily just because you have OCD

**Comment by Tanishq-Banyal** [comment]
And move this pipe_bi to its own directory similar to how fifo and pipe directories are !! this will also help in preserving formatting sanity in existing code

**Comment by Tanishq-Banyal** [comment]
You are not getting through...
I told you already, Don't "format" existing code.

**Comment by eternalfrustation** [comment]
Just merge this code or copy paste it, Please format it yourself
i don's know how you format code

**Comment by Tanishq-Banyal** [comment]
I am asking you "not to" format old code !!

in other words don't change the file in which you didn't add anything new

**Pull request closed without merging**
